---
- name: Test Playbook
  hosts: raspberries
  gather_facts: true
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Upload Bash Script To pi
      ansible.builtin.copy:
        src: /home/pi/ansible/unifi_install.sh
        dest: /home/pnk/unifi_install.sh

    - name: Set Execute permission for
      ansible.builtin.file:
        path: /home/pnk/unifi_install.sh
        mode: u+x

    - name: Update the system
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Curl and CA Certificates
      apt:
        name:
          - curl
          - ca-certificates
        state: present
      become: yes
